#!/bin/zsh
set -euo pipefail

TARGET_DIR="${1:-$PWD/lockin}"

mkdir -p "$TARGET_DIR"/apps/web/{app,components,features,lib,styles}
mkdir -p "$TARGET_DIR"/apps/api/src/{modules,common,config}
mkdir -p "$TARGET_DIR"/apps/worker/src/{jobs,consumers,schedulers}
mkdir -p "$TARGET_DIR"/apps/indexer/src/{chains,projections,backfill,webhooks}
mkdir -p "$TARGET_DIR"/packages/contracts/{src,script,test,abi}
mkdir -p "$TARGET_DIR"/packages/db/{prisma,src}
mkdir -p "$TARGET_DIR"/packages/sdk/src
mkdir -p "$TARGET_DIR"/packages/ui/src
mkdir -p "$TARGET_DIR"/packages/config/{eslint,typescript}
mkdir -p "$TARGET_DIR"/packages/observability/src
mkdir -p "$TARGET_DIR"/infra/{docker,terraform,railway,vercel}
mkdir -p "$TARGET_DIR"/docs
mkdir -p "$TARGET_DIR"/.github/workflows

cat > "$TARGET_DIR/README.md" <<'EOF'
# LockIn Monorepo

Scaffold generated by the `lockin-stablecoin-escrow` plugin.

Core apps:

- `apps/web`: Next.js frontend
- `apps/api`: NestJS API
- `apps/worker`: background jobs and scheduled billing/dispute tasks
- `apps/indexer`: onchain event ingestion and projections

Core packages:

- `packages/contracts`: Solidity contracts, scripts, and tests
- `packages/db`: Prisma schema and shared database helpers
- `packages/sdk`: typed client SDK for frontend and partners
- `packages/ui`: shared UI primitives
- `packages/config`: shared TS and lint config
- `packages/observability`: logging and tracing helpers
EOF

print "Created LockIn monorepo scaffold at: $TARGET_DIR"
